<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tosca2occi" nsURI="http://tosca2occi" nsPrefix="tosca2occi">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
        eType="#//Mapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KindMapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toscaKind" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.cmf.occi.core/model/OCCI.ecore#//Kind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occiTypes" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.cmf.occi.core/model/OCCI.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMapping" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toscaAttribute" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.cmf.occi.core/model/OCCI.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occiAttribute" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.cmf.occi.core/model/OCCI.ecore#//Attribute"/>
  </eClassifiers>
</ecore:EPackage>
